export const PRODUCT_LIST = [
  {
    id: 1,
    name: 'Laptop Pro',
    price: 55000,
    discount: 10,
    stock: 10,
    rating: 4.6,
    cat: 'Electronics',
    sale: true,
    trending: true,
    img: 'https://picsum.photos/id/180/400/400',
  },
  {
    id: 2,
    name: 'Gaming Mouse',
    price: 1200,
    discount: 5,
    stock: 20,
    rating: 4.4,
    cat: 'Electronics',
    sale: false,
    trending: false,
    img: 'https://picsum.photos/id/250/400/400',
  },
  {
    id: 3,
    name: 'Wireless Headphones',
    price: 2400,
    discount: 15,
    stock: 15,
    rating: 4.5,
    cat: 'Electronics',
    sale: true,
    trending: true,
    img: 'https://picsum.photos/id/29/400/400',
  },
  {
    id: 4,
    name: 'Smartwatch X',
    price: 3500,
    discount: 8,
    stock: 12,
    rating: 4.3,
    cat: 'Electronics',
    sale: true,
    trending: false,
    img: 'https://picsum.photos/id/1050/400/400',
  },
  {
    id: 5,
    name: 'Portable Speaker',
    price: 1800,
    discount: 12,
    stock: 18,
    rating: 4.4,
    cat: 'Electronics',
    sale: true,
    trending: false,
    img: 'https://picsum.photos/id/1080/400/400',
  },

  {
    id: 6,
    name: 'Running Shoes',
    price: 2200,
    discount: 5,
    stock: 25,
    rating: 4.2,
    cat: 'Fashion',
    sale: false,
    trending: true,
    img: 'https://picsum.photos/id/21/400/400',
  },
  {
    id: 7,
    name: 'Leather Jacket',
    price: 4800,
    discount: 10,
    stock: 8,
    rating: 4.7,
    cat: 'Fashion',
    sale: true,
    trending: true,
    img: 'https://picsum.photos/id/28/400/400',
  },
  {
    id: 8,
    name: 'Casual T-Shirt',
    price: 600,
    discount: 0,
    stock: 50,
    rating: 3.9,
    cat: 'Fashion',
    sale: false,
    trending: false,
    img: 'https://picsum.photos/id/1060/400/400',
  },
  {
    id: 9,
    name: 'Formal Shirt',
    price: 1200,
    discount: 5,
    stock: 30,
    rating: 4.1,
    cat: 'Fashion',
    sale: false,
    trending: false,
    img: 'https://picsum.photos/id/103/400/400',
  },
  {
    id: 10,
    name: 'Sunglasses Premium',
    price: 1600,
    discount: 7,
    stock: 14,
    rating: 4.3,
    cat: 'Fashion',
    sale: false,
    trending: true,
    img: 'https://picsum.photos/id/290/400/400',
  },

  {
    id: 11,
    name: 'DSLR Camera',
    price: 62000,
    discount: 10,
    stock: 4,
    rating: 4.8,
    cat: 'Electronics',
    sale: true,
    trending: true,
    img: 'https://picsum.photos/id/250/400/400',
  },
  {
    id: 12,
    name: 'Compact Camera',
    price: 18500,
    discount: 5,
    stock: 9,
    rating: 4.2,
    cat: 'Electronics',
    sale: false,
    trending: false,
    img: 'https://picsum.photos/id/460/400/400',
  },
  {
    id: 13,
    name: 'Tripod Stand',
    price: 900,
    discount: 0,
    stock: 20,
    rating: 4.0,
    cat: 'Electronics',
    sale: false,
    trending: false,
    img: 'https://picsum.photos/id/318/400/400',
  },
  {
    id: 14,
    name: 'Camera Lens 50mm',
    price: 12000,
    discount: 10,
    stock: 6,
    rating: 4.7,
    cat: 'Electronics',
    sale: true,
    trending: true,
    img: 'https://picsum.photos/id/303/400/400',
  },
  {
    id: 15,
    name: 'Action Camera',
    price: 5500,
    discount: 8,
    stock: 12,
    rating: 4.5,
    cat: 'Electronics',
    sale: true,
    trending: false,
    img: 'https://picsum.photos/id/1025/400/400',
  },

  {
    id: 16,
    name: 'Office Chair',
    price: 3500,
    discount: 12,
    stock: 10,
    rating: 4.4,
    cat: 'Home',
    sale: true,
    trending: false,
    img: 'https://picsum.photos/id/433/400/400',
  },
  {
    id: 17,
    name: 'Study Table',
    price: 4200,
    discount: 10,
    stock: 8,
    rating: 4.5,
    cat: 'Home',
    sale: true,
    trending: true,
    img: 'https://picsum.photos/id/1076/400/400',
  },
  {
    id: 18,
    name: 'Decor Flower Vase',
    price: 700,
    discount: 0,
    stock: 20,
    rating: 4.0,
    cat: 'Home',
    sale: false,
    trending: false,
    img: 'https://picsum.photos/id/187/400/400',
  },
  {
    id: 19,
    name: 'Wall Clock Modern',
    price: 950,
    discount: 5,
    stock: 18,
    rating: 4.3,
    cat: 'Home',
    sale: false,
    trending: false,
    img: 'https://picsum.photos/id/217/400/400',
  },
  {
    id: 20,
    name: 'Table Lamp',
    price: 1100,
    discount: 8,
    stock: 12,
    rating: 4.4,
    cat: 'Home',
    sale: true,
    trending: false,
    img: 'https://picsum.photos/id/298/400/400',
  },

  {
    id: 21,
    name: 'Sports Water Bottle',
    price: 300,
    discount: 0,
    stock: 50,
    rating: 4.1,
    cat: 'Sports',
    sale: false,
    trending: false,
    img: 'https://picsum.photos/id/493/400/400',
  },
  {
    id: 22,
    name: 'Football',
    price: 800,
    discount: 5,
    stock: 18,
    rating: 4.4,
    cat: 'Sports',
    sale: true,
    trending: false,
    img: 'https://picsum.photos/id/56/400/400',
  },
  {
    id: 23,
    name: 'Badminton Racket',
    price: 1200,
    discount: 10,
    stock: 14,
    rating: 4.5,
    cat: 'Sports',
    sale: true,
    trending: true,
    img: 'https://picsum.photos/id/67/400/400',
  },
  {
    id: 24,
    name: 'Cricket Bat',
    price: 1500,
    discount: 8,
    stock: 10,
    rating: 4.2,
    cat: 'Sports',
    sale: false,
    trending: false,
    img: 'https://picsum.photos/id/78/400/400',
  },
  {
    id: 25,
    name: 'Gym Gloves',
    price: 400,
    discount: 0,
    stock: 40,
    rating: 4.0,
    cat: 'Sports',
    sale: false,
    trending: false,
    img: 'https://picsum.photos/id/85/400/400',
  },

  // More (up to 50 total)
];

for (let i = 26; i <= 70; i++) {
  PRODUCT_LIST.push({
    id: i,
    name: `Product ${i}`,
    price: Math.floor(Math.random() * 5000) + 300,
    discount: Math.floor(Math.random() * 20),
    stock: Math.floor(Math.random() * 20) + 1,
    rating: Number((Math.random() * (5 - 3) + 3).toFixed(1)),
    cat: ['Electronics', 'Fashion', 'Home', 'Sports'][Math.floor(Math.random() * 4)],
    sale: Math.random() > 0.6,
    trending: Math.random() > 0.7,
    img: `https://picsum.photos/id/${100 + i}/400/400`,
  });
}
